#---------------------------------------------------------------DEPLOYMENT---------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-testing
  namespace: app-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcom
  template:
    metadata:
      labels:
        app: testcom
    spec:
      imagePullSecrets:  # <-- FIX: Move this outside 'containers:'
        - name: error-secret
      containers:
        - name: test-container
          image: ghcr.io/saisairepo/loadbalancer:1.0
          ports:
            - containerPort: 9003
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "2"

#------------------------------------------------------------------SERVICE---------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: error-comsvc
  namespace: app-net
spec:
  selector:
    app: testcom
  ports:
    - name: http
      port: 80
      targetPort: 9003
  type: ClusterIP

#-------------------------------------------------------------------INGRESS--------------------------------------------------------------------------------------------
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: errortest-ingress-com
  namespace: app-net
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - oscar.mlhuillier.com
      secretName: com-tls
  rules:
    - host: oscar.mlhuillier.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: error-comsvc
                port:
                  number: 80
