apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-500
  namespace: app-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: errortest
  template:
    metadata:
      labels:
        app: errortest
    spec:
      containers:
      - name: error-container
        image: ghcr.io/saisairepo/loadbalancer:1.1
        ports:
        - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: errorsvc
  namespace: app-net
spec:
  type: LoadBalancer
  selector:
    app: errortest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9002
