#---------------------------------------------------------------DEPLOYMENT---------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-500
  namespace: app-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: errortest
  template:
    metadata:
      labels:
        app: errortest
    spec:
      containers:
      - name: error-container
        image: ghcr.io/saisairepo/loadbalancer:1.0
        ports:
        - containerPort: 9002
        command: ["/bin/sh", "-c", "sleep 3600"]  # Keeps the container alive for debugging
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      imagePullSecrets:
      - name: error-secret
#------------------------------------------------------------------SERVICE---------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: errorsvc
  namespace: app-net
spec:
  selector:
    app: errortest
  ports:
  - name: http
    port: 80
    targetPort: 9002
  type: LoadBalancer
